-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity JetTagger_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config22_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of JetTagger_dense_latency_ap_ufixed_9_0_4_0_0_ap_fixed_16_6_5_3_0_config22_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv17_83 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000011";
    constant ap_const_lv17_1FFB3 : STD_LOGIC_VECTOR (16 downto 0) := "11111111110110011";
    constant ap_const_lv16_6D : STD_LOGIC_VECTOR (15 downto 0) := "0000000001101101";
    constant ap_const_lv17_AF : STD_LOGIC_VECTOR (16 downto 0) := "00000000010101111";
    constant ap_const_lv16_6A : STD_LOGIC_VECTOR (15 downto 0) := "0000000001101010";
    constant ap_const_lv18_3FF5C : STD_LOGIC_VECTOR (17 downto 0) := "111111111101011100";
    constant ap_const_lv18_3FF63 : STD_LOGIC_VECTOR (17 downto 0) := "111111111101100011";
    constant ap_const_lv17_85 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000101";
    constant ap_const_lv19_2A1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001010100001";
    constant ap_const_lv16_64 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001100100";
    constant ap_const_lv17_EE : STD_LOGIC_VECTOR (16 downto 0) := "00000000011101110";
    constant ap_const_lv17_AC : STD_LOGIC_VECTOR (16 downto 0) := "00000000010101100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv9_1E4 : STD_LOGIC_VECTOR (8 downto 0) := "111100100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

attribute shreg_extract : string;
    signal data_18_val_read_reg_2197 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_18_val_read_reg_2197_pp0_iter1_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_reg_2203 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln42_s_reg_2208 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_382_reg_2213 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln42_1_reg_2218 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln42_2_reg_2223 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_383_reg_2228 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_384_reg_2233 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_386_reg_2238 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_386_reg_2238_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_387_reg_2248 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_388_reg_2253 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_389_reg_2258 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln42_22_cast_reg_2263 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_80_fu_2045_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_80_reg_2268 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_83_fu_2071_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_83_reg_2273 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_89_fu_2097_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_89_reg_2278 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_89_reg_2278_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_89_reg_2278_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_385_reg_2283 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_84_fu_2150_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_84_reg_2288 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_84_reg_2288_pp0_iter3_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_84_reg_2288_pp0_iter4_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_85_fu_2156_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_85_reg_2293 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_86_fu_2167_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_86_reg_2298 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_90_fu_2179_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_90_reg_2303 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln73_5_fu_175_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_5_fu_175_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln73_4_fu_178_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_4_fu_178_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln42_1_fu_179_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_1_fu_179_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_8_fu_180_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_8_fu_180_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_2_fu_185_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_2_fu_185_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_3_fu_188_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_3_fu_188_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_1_fu_191_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_1_fu_191_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_6_fu_195_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_6_fu_195_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_198_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_198_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_201_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_fu_201_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln73_2_fu_202_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_2_fu_202_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_fu_203_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_fu_203_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_fu_203_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_1_fu_191_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_2_fu_202_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_3_fu_188_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_4_fu_178_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_5_fu_175_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_6_fu_195_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln42_fu_201_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_8_fu_180_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln42_1_fu_179_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_2_fu_185_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_198_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln70_fu_1998_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln70_10_fu_2001_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_fu_2035_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_32_fu_2041_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln70_9_fu_1995_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln70_1_fu_2004_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_2_fu_2007_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_81_fu_2051_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln42_11_cast_fu_2010_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal lshr_ln42_15_cast_fu_2013_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_82_fu_2061_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_fu_2067_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_34_fu_2057_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln42_4_fu_2026_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln42_5_fu_2029_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_87_fu_2077_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_144_fu_2032_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln58_88_fu_2087_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln58_fu_2093_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_130_fu_2083_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_fu_2103_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln73_s_fu_2114_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_fu_2110_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln73_1_fu_2121_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln73_fu_2125_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln58_35_fu_2147_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_33_fu_2144_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln42_19_cast_fu_2141_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_128_fu_2164_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln42_3_fu_2161_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_37_fu_2176_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln58_129_fu_2173_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_38_fu_2188_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln58_36_fu_2185_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_198_ce : STD_LOGIC;
    signal add_ln58_91_fu_2191_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal data_0_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_3_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_4_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_6_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_9_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_11_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_15_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_18_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_19_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_22_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_25_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_28_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal data_31_val_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_198_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln42_1_fu_179_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_2_fu_185_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_201_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_1_fu_191_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_2_fu_202_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_3_fu_188_p00 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln73_4_fu_178_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_5_fu_175_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_6_fu_195_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_8_fu_180_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln73_fu_203_p00 : STD_LOGIC_VECTOR (16 downto 0);

    component JetTagger_mul_9ns_9ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component JetTagger_mul_9ns_8s_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component JetTagger_mul_9ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component JetTagger_mul_9ns_9s_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component JetTagger_mul_9ns_11ns_19_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    mul_9ns_9ns_17_1_1_U5972 : component JetTagger_mul_9ns_9ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_5_fu_175_p0,
        din1 => mul_ln73_5_fu_175_p1,
        dout => mul_ln73_5_fu_175_p2);

    mul_9ns_8s_17_1_1_U5973 : component JetTagger_mul_9ns_8s_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_4_fu_178_p0,
        din1 => mul_ln73_4_fu_178_p1,
        dout => mul_ln73_4_fu_178_p2);

    mul_9ns_8ns_16_1_1_U5974 : component JetTagger_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln42_1_fu_179_p0,
        din1 => mul_ln42_1_fu_179_p1,
        dout => mul_ln42_1_fu_179_p2);

    mul_9ns_9ns_17_1_1_U5975 : component JetTagger_mul_9ns_9ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_8_fu_180_p0,
        din1 => mul_ln73_8_fu_180_p1,
        dout => mul_ln73_8_fu_180_p2);

    mul_9ns_8ns_16_1_1_U5976 : component JetTagger_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln42_2_fu_185_p0,
        din1 => mul_ln42_2_fu_185_p1,
        dout => mul_ln42_2_fu_185_p2);

    mul_9ns_9s_18_1_1_U5977 : component JetTagger_mul_9ns_9s_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_3_fu_188_p0,
        din1 => mul_ln73_3_fu_188_p1,
        dout => mul_ln73_3_fu_188_p2);

    mul_9ns_9s_18_1_1_U5978 : component JetTagger_mul_9ns_9s_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 18)
    port map (
        din0 => mul_ln73_1_fu_191_p0,
        din1 => mul_ln73_1_fu_191_p1,
        dout => mul_ln73_1_fu_191_p2);

    mul_9ns_9ns_17_1_1_U5979 : component JetTagger_mul_9ns_9ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_6_fu_195_p0,
        din1 => mul_ln73_6_fu_195_p1,
        dout => mul_ln73_6_fu_195_p2);

    mul_9ns_11ns_19_2_0_U5980 : component JetTagger_mul_9ns_11ns_19_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_198_p0,
        din1 => grp_fu_198_p1,
        ce => grp_fu_198_ce,
        dout => grp_fu_198_p2);

    mul_9ns_8ns_16_1_1_U5981 : component JetTagger_mul_9ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln42_fu_201_p0,
        din1 => mul_ln42_fu_201_p1,
        dout => mul_ln42_fu_201_p2);

    mul_9ns_9ns_17_1_1_U5982 : component JetTagger_mul_9ns_9ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_2_fu_202_p0,
        din1 => mul_ln73_2_fu_202_p1,
        dout => mul_ln73_2_fu_202_p2);

    mul_9ns_9ns_17_1_1_U5983 : component JetTagger_mul_9ns_9ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln73_fu_203_p0,
        din1 => mul_ln73_fu_203_p1,
        dout => mul_ln73_fu_203_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln58_80_reg_2268 <= add_ln58_80_fu_2045_p2;
                add_ln58_83_reg_2273 <= add_ln58_83_fu_2071_p2;
                add_ln58_84_reg_2288 <= add_ln58_84_fu_2150_p2;
                add_ln58_84_reg_2288_pp0_iter3_reg <= add_ln58_84_reg_2288;
                add_ln58_84_reg_2288_pp0_iter4_reg <= add_ln58_84_reg_2288_pp0_iter3_reg;
                add_ln58_85_reg_2293 <= add_ln58_85_fu_2156_p2;
                add_ln58_86_reg_2298 <= add_ln58_86_fu_2167_p2;
                add_ln58_89_reg_2278 <= add_ln58_89_fu_2097_p2;
                add_ln58_89_reg_2278_pp0_iter2_reg <= add_ln58_89_reg_2278;
                add_ln58_89_reg_2278_pp0_iter3_reg <= add_ln58_89_reg_2278_pp0_iter2_reg;
                add_ln58_90_reg_2303 <= add_ln58_90_fu_2179_p2;
                data_18_val_read_reg_2197 <= data_18_val_int_reg;
                data_18_val_read_reg_2197_pp0_iter1_reg <= data_18_val_read_reg_2197;
                lshr_ln42_22_cast_reg_2263 <= grp_fu_198_p2(18 downto 8);
                tmp_382_reg_2213 <= mul_ln73_2_fu_202_p2(16 downto 8);
                tmp_383_reg_2228 <= mul_ln73_5_fu_175_p2(16 downto 8);
                tmp_384_reg_2233 <= mul_ln73_6_fu_195_p2(16 downto 8);
                tmp_385_reg_2283 <= add_ln73_fu_2125_p2(17 downto 8);
                tmp_386_reg_2238 <= mul_ln42_fu_201_p2(15 downto 8);
                tmp_386_reg_2238_pp0_iter1_reg <= tmp_386_reg_2238;
                tmp_387_reg_2248 <= mul_ln73_8_fu_180_p2(16 downto 8);
                tmp_388_reg_2253 <= mul_ln42_1_fu_179_p2(15 downto 8);
                tmp_389_reg_2258 <= mul_ln42_2_fu_185_p2(15 downto 8);
                tmp_reg_2203 <= mul_ln73_fu_203_p2(16 downto 8);
                trunc_ln42_1_reg_2218 <= mul_ln73_3_fu_188_p2(17 downto 8);
                trunc_ln42_2_reg_2223 <= mul_ln73_4_fu_178_p2(16 downto 8);
                trunc_ln42_s_reg_2208 <= mul_ln73_1_fu_191_p2(17 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= add_ln58_91_fu_2191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                data_0_val_int_reg <= data_0_val;
                data_11_val_int_reg <= data_11_val;
                data_15_val_int_reg <= data_15_val;
                data_18_val_int_reg <= data_18_val;
                data_19_val_int_reg <= data_19_val;
                data_22_val_int_reg <= data_22_val;
                data_25_val_int_reg <= data_25_val;
                data_28_val_int_reg <= data_28_val;
                data_31_val_int_reg <= data_31_val;
                data_3_val_int_reg <= data_3_val;
                data_4_val_int_reg <= data_4_val;
                data_6_val_int_reg <= data_6_val;
                data_9_val_int_reg <= data_9_val;
            end if;
        end if;
    end process;
    add_ln58_80_fu_2045_p2 <= std_logic_vector(signed(sext_ln58_32_fu_2041_p1) + signed(zext_ln70_9_fu_1995_p1));
    add_ln58_81_fu_2051_p2 <= std_logic_vector(signed(sext_ln70_1_fu_2004_p1) + signed(sext_ln70_2_fu_2007_p1));
    add_ln58_82_fu_2061_p2 <= std_logic_vector(unsigned(lshr_ln42_11_cast_fu_2010_p1) + unsigned(lshr_ln42_15_cast_fu_2013_p1));
    add_ln58_83_fu_2071_p2 <= std_logic_vector(unsigned(zext_ln58_fu_2067_p1) + unsigned(sext_ln58_34_fu_2057_p1));
    add_ln58_84_fu_2150_p2 <= std_logic_vector(signed(sext_ln58_35_fu_2147_p1) + signed(sext_ln58_33_fu_2144_p1));
    add_ln58_85_fu_2156_p2 <= std_logic_vector(unsigned(lshr_ln42_19_cast_fu_2141_p1) + unsigned(lshr_ln42_22_cast_reg_2263));
    add_ln58_86_fu_2167_p2 <= std_logic_vector(unsigned(zext_ln58_128_fu_2164_p1) + unsigned(zext_ln42_3_fu_2161_p1));
    add_ln58_87_fu_2077_p2 <= std_logic_vector(unsigned(zext_ln42_4_fu_2026_p1) + unsigned(zext_ln42_5_fu_2029_p1));
    add_ln58_88_fu_2087_p2 <= std_logic_vector(unsigned(zext_ln58_144_fu_2032_p1) + unsigned(ap_const_lv9_1E4));
    add_ln58_89_fu_2097_p2 <= std_logic_vector(signed(sext_ln58_fu_2093_p1) + signed(zext_ln58_130_fu_2083_p1));
    add_ln58_90_fu_2179_p2 <= std_logic_vector(signed(sext_ln58_37_fu_2176_p1) + signed(zext_ln58_129_fu_2173_p1));
    add_ln58_91_fu_2191_p2 <= std_logic_vector(signed(sext_ln58_38_fu_2188_p1) + signed(sext_ln58_36_fu_2185_p1));
    add_ln58_fu_2035_p2 <= std_logic_vector(signed(sext_ln70_fu_1998_p1) + signed(zext_ln70_10_fu_2001_p1));
    add_ln73_fu_2125_p2 <= std_logic_vector(unsigned(zext_ln73_fu_2110_p1) + unsigned(zext_ln73_1_fu_2121_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(add_ln58_91_fu_2191_p2, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= add_ln58_91_fu_2191_p2;
        else 
            ap_return <= "XXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_198_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_198_ce <= ap_const_logic_1;
        else 
            grp_fu_198_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_198_p0 <= grp_fu_198_p00(9 - 1 downto 0);
    grp_fu_198_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_22_val_int_reg),19));
    grp_fu_198_p1 <= ap_const_lv19_2A1(11 - 1 downto 0);
    lshr_ln42_11_cast_fu_2010_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_383_reg_2228),10));
    lshr_ln42_15_cast_fu_2013_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_384_reg_2233),10));
    lshr_ln42_19_cast_fu_2141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_386_reg_2238_pp0_iter1_reg),11));
    mul_ln42_1_fu_179_p0 <= mul_ln42_1_fu_179_p00(9 - 1 downto 0);
    mul_ln42_1_fu_179_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_28_val_int_reg),16));
    mul_ln42_1_fu_179_p1 <= ap_const_lv16_6D(8 - 1 downto 0);
    mul_ln42_2_fu_185_p0 <= mul_ln42_2_fu_185_p00(9 - 1 downto 0);
    mul_ln42_2_fu_185_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_31_val_int_reg),16));
    mul_ln42_2_fu_185_p1 <= ap_const_lv16_6A(8 - 1 downto 0);
    mul_ln42_fu_201_p0 <= mul_ln42_fu_201_p00(9 - 1 downto 0);
    mul_ln42_fu_201_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_19_val_int_reg),16));
    mul_ln42_fu_201_p1 <= ap_const_lv16_64(8 - 1 downto 0);
    mul_ln73_1_fu_191_p0 <= mul_ln73_1_fu_191_p00(9 - 1 downto 0);
    mul_ln73_1_fu_191_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_3_val_int_reg),18));
    mul_ln73_1_fu_191_p1 <= ap_const_lv18_3FF63(9 - 1 downto 0);
    mul_ln73_2_fu_202_p0 <= mul_ln73_2_fu_202_p00(9 - 1 downto 0);
    mul_ln73_2_fu_202_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_4_val_int_reg),17));
    mul_ln73_2_fu_202_p1 <= ap_const_lv17_EE(9 - 1 downto 0);
    mul_ln73_3_fu_188_p0 <= mul_ln73_3_fu_188_p00(9 - 1 downto 0);
    mul_ln73_3_fu_188_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_6_val_int_reg),18));
    mul_ln73_3_fu_188_p1 <= ap_const_lv18_3FF5C(9 - 1 downto 0);
    mul_ln73_4_fu_178_p0 <= mul_ln73_4_fu_178_p00(9 - 1 downto 0);
    mul_ln73_4_fu_178_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_9_val_int_reg),17));
    mul_ln73_4_fu_178_p1 <= ap_const_lv17_1FFB3(8 - 1 downto 0);
    mul_ln73_5_fu_175_p0 <= mul_ln73_5_fu_175_p00(9 - 1 downto 0);
    mul_ln73_5_fu_175_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_11_val_int_reg),17));
    mul_ln73_5_fu_175_p1 <= ap_const_lv17_83(9 - 1 downto 0);
    mul_ln73_6_fu_195_p0 <= mul_ln73_6_fu_195_p00(9 - 1 downto 0);
    mul_ln73_6_fu_195_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_15_val_int_reg),17));
    mul_ln73_6_fu_195_p1 <= ap_const_lv17_85(9 - 1 downto 0);
    mul_ln73_8_fu_180_p0 <= mul_ln73_8_fu_180_p00(9 - 1 downto 0);
    mul_ln73_8_fu_180_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_25_val_int_reg),17));
    mul_ln73_8_fu_180_p1 <= ap_const_lv17_AF(9 - 1 downto 0);
    mul_ln73_fu_203_p0 <= mul_ln73_fu_203_p00(9 - 1 downto 0);
    mul_ln73_fu_203_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_0_val_int_reg),17));
    mul_ln73_fu_203_p1 <= ap_const_lv17_AC(9 - 1 downto 0);
        sext_ln58_32_fu_2041_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_fu_2035_p2),12));

        sext_ln58_33_fu_2144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_80_reg_2268),13));

        sext_ln58_34_fu_2057_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_81_fu_2051_p2),12));

        sext_ln58_35_fu_2147_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_83_reg_2273),13));

        sext_ln58_36_fu_2185_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_84_reg_2288_pp0_iter4_reg),14));

        sext_ln58_37_fu_2176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_89_reg_2278_pp0_iter3_reg),13));

        sext_ln58_38_fu_2188_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_90_reg_2303),14));

        sext_ln58_fu_2093_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_88_fu_2087_p2),11));

        sext_ln70_1_fu_2004_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_1_reg_2218),11));

        sext_ln70_2_fu_2007_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_2_reg_2223),11));

        sext_ln70_fu_1998_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_s_reg_2208),11));

    shl_ln73_s_fu_2114_p3 <= (data_18_val_read_reg_2197_pp0_iter1_reg & ap_const_lv1_0);
    shl_ln_fu_2103_p3 <= (data_18_val_read_reg_2197_pp0_iter1_reg & ap_const_lv8_0);
    zext_ln42_3_fu_2161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_385_reg_2283),12));
    zext_ln42_4_fu_2026_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_387_reg_2248),10));
    zext_ln42_5_fu_2029_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_388_reg_2253),10));
    zext_ln58_128_fu_2164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_85_reg_2293),12));
    zext_ln58_129_fu_2173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_86_reg_2298),13));
    zext_ln58_130_fu_2083_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_87_fu_2077_p2),11));
    zext_ln58_144_fu_2032_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_389_reg_2258),9));
    zext_ln58_fu_2067_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_82_fu_2061_p2),12));
    zext_ln70_10_fu_2001_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_382_reg_2213),11));
    zext_ln70_9_fu_1995_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_2203),12));
    zext_ln73_1_fu_2121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln73_s_fu_2114_p3),18));
    zext_ln73_fu_2110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_2103_p3),18));
end behav;
