Backend: Vitis
ClockPeriod: 2.8
HLSConfig:
  LayerName:
    avgpool:
      Precision:
        result: fixed<16,6>
      Trace: false
    batchnorm_inputs:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    inputs:
      Precision:
        result: fixed<16,6>
      Trace: false
    output_class:
      Precision:
        result: fixed<16,6>
      Trace: false
    output_reg:
      Precision:
        result: fixed<16,6>
      Trace: false
    qActivationForPool:
      Precision:
        result: fixed<18,9,RND_CONV,SAT>
      Trace: false
    qActivation_2_class:
      Precision:
        result: ufixed<9,0,RND_CONV,SAT>
      Trace: false
    qActivation_2_reg:
      Precision:
        result: ufixed<9,0,RND_CONV,SAT>
      Trace: false
    qActivation_phi_1:
      Precision:
        result: ufixed<9,0,RND_CONV,SAT>
      Trace: false
    qActivation_phi_2:
      Precision:
        result: ufixed<9,0,RND_CONV,SAT>
      Trace: false
    qActivation_rho_1:
      Precision:
        result: ufixed<9,0,RND_CONV,SAT>
      Trace: false
    qDense_2_class:
      Precision:
        bias: fixed<9,3>
        result: fixed<16,6>
        weight: fixed<9,3>
      Trace: false
    qDense_2_class_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_2_reg:
      Precision:
        bias: fixed<9,3>
        result: fixed<16,6>
        weight: fixed<9,3>
      Trace: false
    qDense_2_reg_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_out_class:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,6>
        weight: fixed<16,7>
      Trace: false
    qDense_out_class_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_out_reg:
      Precision:
        bias: fixed<16,7>
        result: fixed<16,6>
        weight: fixed<16,7>
      Trace: false
    qDense_out_reg_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_phi_1:
      Precision:
        bias: fixed<9,3>
        result: fixed<16,6>
        weight: fixed<9,3>
      Trace: false
    qDense_phi_1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_phi_2:
      Precision:
        bias: fixed<9,3>
        result: fixed<16,6>
        weight: fixed<9,3>
      Trace: false
    qDense_phi_2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    qDense_rho_1:
      Precision:
        bias: fixed<9,3>
        result: fixed<16,6>
        weight: fixed<9,3>
      Trace: false
    qDense_rho_1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'JetTaggerNN/keras_model.h5'
OutputDir: JetTaggerNN
OutputPredictions: null
Part: xcvu9p-flga2104-2L-e
ProjectName: JetTaggerNN
Stamp: c938edBE
Version: 1.0.0
