name: L1_Tagger
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - tensorflow==2.14
    - pyparsing
    - git+https://github.com/fastmachinelearning/qonnx.git
    - git+https://github.com/jmitrevs/qkeras.git@qrecurrent_unstack
